name: Generate PDF Preview

on:
  push:
    paths:
      - '*.pdf'
  workflow_dispatch:

jobs:
  generate-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ghostscript


      - name: Generate preview from PDF
        run: |
          mkdir -p preview
          convert -density 150 resume_en.pdf[0] -quality 90 preview/preview.png

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add preview/preview.png
          git commit -m "Automated preview update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
